"""
Train a model on the MMS Dataset.
"""

import numpy as np
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.optim.lr_scheduler as sched
import torch.utils.data as data
import util

from args import get_train_args
from collections import OrderedDict
from json import dumps
from models import MMBiDAF
from tensorboardX import SummaryWriter
from tqdm import tqdm
from ujson import load as json_load
from util import collate_fn # importing SQuAD is not required

def main(args):
    # Set up logging and devices
    args.save_dir = util.get_save_dir(args.save_dir, args.name, training=True)
    log = util.get_logger(args.save_dir, args.name)
    tbx = SummaryWriter(args.save_dir)
    device, args.gpu_ids = util.get_available_devices()
    log.info('Args: {}'.format(dumps(vars(args), indent=4, sort_keys=True)))
    args.batch_size *= max(1, len(args.gpu_ids))

    # Set random seed
    log.info('Using random seed {}...'.format(args.seed))
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)

    # Get embeddings
    """
    The embeddings need to be imported from the
    sentence embeddings generated by using gensim.
    """
    log.info('Loading embeddings...')
    word_vectors = util.torch_from_json(args.word_emb_file)

    # Place checkpoint 

    # Get Audio embeddings
    """
    The mebeddings need to be imported from the 
    """

    # Get model
    log.info('Building model')
    model = MMBiDAF(word_vector = word_vectors,
                    audio_vectors = audio_vectors,
                    image_vectors = image_vectors,
                    hidden_size = args.hidden_size,
                    drop_prob = args.drop_prob)
